services:
  limited-service:
    container_name: limited-service
    image: sohyun119/limited-service:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        SECRET_KEY: ${SECRET_KEY}
    ports:
      - '19095:19095'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 1024mb
    cpus: 1
    networks:
      - limited-team25

networks:
  limited-team25:
    external: true