server:
  port: 19095

spring:
  application:
    name: limited-service

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/eureka.yml
      - classpath:properties/prometheus.yml

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
