server:
  port: 19095

spring:
  application:
    name: limited-service

  config:
    import:
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/eureka.yml
