global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'limited-service-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:19095' ]

  - job_name: 'product-service-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:19093' ]