### 한정수량 상품 생성
POST http://localhost:8081/api/v1/limited-products/b373def5-9b53-42cd-ab09-b07caf26189c
Content-Type: application/json
X-User-Id: 123

{
  "quantity": 10
}

### 한정수량 상품 단일 조회
GET http://localhost:8081/api/v1/limited-products/6340b658-29fc-43ea-a672-c806781b756a
Content-Type: application/json

### 한정수량 상품 재고 수량 (감소) 수정
PUT http://localhost:8081/api/v1/limited-products/6340b658-29fc-43ea-a672-c806781b756a/quantity
Content-Type: application/json
